include:
  # Storage
  - path: docker/storage/postgres.yml
    project_directory: .

  # Auth service
  - path: docker/auth/compose.override.yml
    project_directory: .

  # Payments service
  - path: docker/payments/compose.override.yml
    project_directory: .

  # Email service
  - path: docker/email/compose.override.yml
    project_directory: .
