services:
  app:
    build:
      context: ..
      target: development
    entrypoint: ["/bin/sh", "docker/entrypoint.sh"]
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    volumes:
      - ${PWD}/libs/common/src:/usr/src/app/libs/common/src
      - ${PWD}/proto:/usr/src/app/proto
